In [75]:
import pandas as pd

In [107]:
a = pd.read_csv('automl_5_200227.csv')

In [108]:
a['date'] = pd.to_datetime(a['date'], format='%Y-%m-%d', errors='ignore')

In [109]:
#a.set_index('date', inplace = True)

In [110]:
#a.to_csv('automl_260_200227.csv')

In [111]:
len(a.loc[4546:])

505

In [112]:
b = a.loc[4546:]

In [113]:
b.reset_index(inplace = True, drop = True)

In [114]:
b.head()

,date,GDPCQOQIndex,GDPCYOYIndex,GDPCTOTIndex,GPDITOCIndex,GPGSTOCIndex,RGCDCIPIIndex,GDPCURIndex,GDPCURYIndex,GDPPIQQIndex,...,Nvidia_product,Philadelphia_product,QCOM_product,ShinEtsuChemical_product,Siltronic_product,SKhynix_product,Sumco_product,TokyoElectron_product,TSMC_product,UMC_product
0,2018-06-14,3.317091,3.151277,3.546236,-2.055321,2.423474,-26.558691,20450.95632,5.872843,3.152974,...,1.292525,0.951517,0.868174,0.577902,1.080397,1.289615,0.634060,1.210298,0.996124,0.323529
1,2018-06-15,3.330223,3.154642,3.579007,-2.083733,2.435273,-26.953685,20454.79069,5.882098,3.159286,...,0.999365,1.714843,1.659837,1.250209,0.935965,0.638891,0.949438,1.309422,1.357043,2.252817
2,2018-06-16,3.343172,3.157972,3.611313,-2.106808,2.447004,-27.312258,20458.61005,5.891201,3.165196,...,0.745678,1.054642,1.024973,0.839123,0.990933,0.983793,0.859866,1.169281,1.286546,1.218599
3,2018-06-17,3.355929,3.161263,3.643129,-2.124422,2.458662,-27.633503,20462.41383,5.900148,3.170696,...,0.750686,0.747246,0.697030,0.897208,1.026427,1.419122,0.800145,1.090073,1.123877,0.657044
4,2018-06-18,3.368484,3.164516,3.674427,-2.136452,2.470237,-27.916512,20466.20144,5.908934,3.175774,...,1.471513,0.751156,0.697151,2.162350,0.968889,1.109309,1.168558,1.000298,0.988917,0.445246

In [115]:
#b.drop('date', axis = 1, inplace = True)

In [116]:
b.reset_index(inplace = True, drop = True)

In [117]:
b.set_index('date', inplace = True)

In [118]:
b.head()

,GDPCQOQIndex,GDPCYOYIndex,GDPCTOTIndex,GPDITOCIndex,GPGSTOCIndex,RGCDCIPIIndex,GDPCURIndex,GDPCURYIndex,GDPPIQQIndex,GDPCPCECIndex,...,Nvidia_product,Philadelphia_product,QCOM_product,ShinEtsuChemical_product,Siltronic_product,SKhynix_product,Sumco_product,TokyoElectron_product,TSMC_product,UMC_product
date,,,,,,,,,,,,,,,,,,,,,
2018-06-14,3.317091,3.151277,3.546236,-2.055321,2.423474,-26.558691,20450.95632,5.872843,3.152974,2.172142,...,1.292525,0.951517,0.868174,0.577902,1.080397,1.289615,0.634060,1.210298,0.996124,0.323529
2018-06-15,3.330223,3.154642,3.579007,-2.083733,2.435273,-26.953685,20454.79069,5.882098,3.159286,2.168319,...,0.999365,1.714843,1.659837,1.250209,0.935965,0.638891,0.949438,1.309422,1.357043,2.252817
2018-06-16,3.343172,3.157972,3.611313,-2.106808,2.447004,-27.312258,20458.61005,5.891201,3.165196,2.164409,...,0.745678,1.054642,1.024973,0.839123,0.990933,0.983793,0.859866,1.169281,1.286546,1.218599
2018-06-17,3.355929,3.161263,3.643129,-2.124422,2.458662,-27.633503,20462.41383,5.900148,3.170696,2.160413,...,0.750686,0.747246,0.697030,0.897208,1.026427,1.419122,0.800145,1.090073,1.123877,0.657044
2018-06-18,3.368484,3.164516,3.674427,-2.136452,2.470237,-27.916512,20466.20144,5.908934,3.175774,2.156328,...,1.471513,0.751156,0.697151,2.162350,0.968889,1.109309,1.168558,1.000298,0.988917,0.445246

In [119]:
b.to_csv('automltest_5.csv')