# 대상 데이터프레임과 타겟컬럼을 지정하면 1일, 7일, 30일, 90일, 180일, 365일 단위로 return 뱉는 function

## EX : 1day return = nextday close / base day close

In [1]:
import pandas as pd

In [6]:
df = pd.read_csv('semiconductor_bloomberg_raw_20200109.csv', index_col = 0)

In [7]:
df.head()

,date,GDPCQOQIndex,GDPCYOYIndex,GDPCTOT%Index,GPDITOC%Index,GPGSTOC%Index,RGCDCIPIIndex,GDPCUR$Index,GDPCURYIndex,GDPPIQQIndex,...,KOMSLYIndex,KOMSM1FYIndex,KOFETOTIndex,KOFETOT%Index,KORP7DIndex,KOCICOBAIndex,KOCICONFIndex,KRBO3MIndex,KWCDCCurncy,GVSK10YRIndex
0,1981-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1981-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1981-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1981-01-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1981-01-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df.set_index('date', inplace = True)

In [14]:
# df should involve datetime index
# target column example = 'SKhynix_close'
def make_return_columns(df, target_column):
    # lagging day list
    lag_days = [1, 7, 30, 90, 180, 365]
    
    col_name =  []
    # creating new column name
    for i in lag_days:
        col_name.append(target_column + str(i))
    # appending lagged columns
    for i, j in enumerate(lag_days):
        df[locals()['col_name'][i]] = df[target_column]/df[target_column].shift(periods = j, axis = 0)
    return df

In [34]:
df['USGG10YRIndex']

date
1981-01-01        NaN
1981-01-02    12.4220
1981-01-05    12.1520
1981-01-06    12.1120
1981-01-07    12.3820
               ...
2019-10-27        NaN
2019-10-28     1.8420
2019-10-29     1.8385
2019-10-30     1.7715
2019-10-31     1.6910
Name: USGG10YRIndex, Length: 11682, dtype: float64

In [42]:
new_df = df[['USGG10YRIndex', 'GPGSTOC%Index']]

In [43]:
new_df

            USGG10YRIndex  GPGSTOC%Index
date
1981-01-01            NaN            NaN
1981-01-02        12.4220            NaN
1981-01-05        12.1520            NaN
1981-01-06        12.1120            NaN
1981-01-07        12.3820            NaN
...                   ...            ...
2019-10-27            NaN            NaN
2019-10-28         1.8420            NaN
2019-10-29         1.8385            NaN
2019-10-30         1.7715            NaN
2019-10-31         1.6910            NaN

[11682 rows x 2 columns]

In [44]:
make_return_columns(new_df, 'USGG10YRIndex')

/Users/mokpolar/opt/anaconda3/envs/tf-py36/lib/python3.6/site-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]

,USGG10YRIndex,GPGSTOC%Index,USGG10YRIndex1,USGG10YRIndex7,USGG10YRIndex30,USGG10YRIndex90,USGG10YRIndex180,USGG10YRIndex365
date,,,,,,,,
1981-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1981-01-02,12.4220,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1981-01-05,12.1520,NaN,0.978264,NaN,NaN,NaN,NaN,NaN
1981-01-06,12.1120,NaN,0.996708,NaN,NaN,NaN,NaN,NaN
1981-01-07,12.3820,NaN,1.022292,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
2019-10-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-10-28,1.8420,NaN,NaN,NaN,1.066775,0.876058,0.744513,0.638696
2019-10-29,1.8385,NaN,0.998100,1.021786,1.117222,0.898978,0.728378,0.643958
2019-10-30,1.7715,NaN,0.963557,1.006134,1.019744,0.875161,0.704346,0.619319
2019-10-31,1.6910,NaN,0.954558,0.958508,0.999350,0.822791,0.677647,NaN

In [47]:
new_df.head(50)

,USGG10YRIndex,GPGSTOC%Index,USGG10YRIndex1,USGG10YRIndex7,USGG10YRIndex30,USGG10YRIndex90,USGG10YRIndex180,USGG10YRIndex365
date,,,,,,,,
1981-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1981-01-02,12.422,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1981-01-05,12.152,NaN,0.978264,NaN,NaN,NaN,NaN,NaN
1981-01-06,12.112,NaN,0.996708,NaN,NaN,NaN,NaN,NaN
1981-01-07,12.382,NaN,1.022292,NaN,NaN,NaN,NaN,NaN
1981-01-08,12.352,NaN,0.997577,NaN,NaN,NaN,NaN,NaN
1981-01-09,12.572,NaN,1.017811,NaN,NaN,NaN,NaN,NaN
1981-01-12,12.452,NaN,0.990455,NaN,NaN,NaN,NaN,NaN
1981-01-13,12.532,NaN,1.006425,1.008855,NaN,NaN,NaN,NaN
1981-01-14,12.532,NaN,1.000000,1.031271,NaN,NaN,NaN,NaN
1981-01-15,12.622,NaN,1.007182,1.042107,NaN,NaN,NaN,NaN
1981-01-16,12.532,NaN,0.992870,1.012114,NaN,NaN,NaN,NaN
1981-01-19,12.642,NaN,1.008778,1.023478,NaN,NaN,NaN,NaN
1981-01-20,12.502,NaN,0.988926,0.994432,NaN,NaN,NaN,NaN
1981-01-21,12.772,NaN,1.021597,1.025699,NaN,NaN,NaN,NaN
1981-01-22,12.872,NaN,1.007830,1.027131,NaN,NaN,NaN,NaN
1981-01-23,12.842,NaN,0.997669,1.024737,NaN,NaN,NaN,NaN
1981-01-26,12.702,NaN,0.989098,1.006338,NaN,NaN,NaN,NaN
1981-01-27,12.732,NaN,1.002362,1.015959,NaN,NaN,NaN,NaN
1981-01-28,12.772,NaN,1.003142,1.010283,NaN,NaN,NaN,NaN
1981-01-29,12.802,NaN,1.002349,1.023996,NaN,NaN,NaN,NaN
1981-01-30,12.682,NaN,0.990626,0.992953,NaN,NaN,NaN,NaN
1981-01-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1981-02-02,12.862,NaN,NaN,1.001557,NaN,NaN,NaN,NaN
1981-02-03,12.982,NaN,1.009330,1.022044,NaN,NaN,NaN,NaN
1981-02-04,12.862,NaN,0.990756,1.010210,NaN,NaN,NaN,NaN
1981-02-05,12.952,NaN,1.006997,1.014093,NaN,NaN,NaN,NaN
1981-02-06,13.092,NaN,1.010809,1.022653,NaN,NaN,NaN,NaN
1981-02-09,13.212,NaN,1.009166,1.041792,NaN,NaN,NaN,NaN
1981-02-10,13.272,NaN,1.004541,NaN,NaN,NaN,NaN,NaN
1981-02-11,13.422,NaN,1.011302,1.043539,NaN,NaN,NaN,NaN
1981-02-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1981-02-13,13.652,NaN,NaN,1.061421,1.123436,NaN,NaN,NaN
1981-02-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1981-02-17,13.332,NaN,NaN,1.018332,1.076724,NaN,NaN,NaN
1981-02-18,13.302,NaN,0.997750,1.006812,1.076911,NaN,NaN,NaN
1981-02-19,13.092,NaN,0.984213,0.986438,1.041362,NaN,NaN,NaN
1981-02-20,12.902,NaN,0.985487,0.961258,1.036139,NaN,NaN,NaN
1981-02-23,13.192,NaN,1.022477,NaN,1.052665,NaN,NaN,NaN
1981-02-24,13.212,NaN,1.001516,0.967770,1.054261,NaN,NaN,NaN
1981-02-25,13.292,NaN,1.006055,NaN,1.053082,NaN,NaN,NaN
1981-02-26,13.472,NaN,1.013542,1.010501,1.075008,NaN,NaN,NaN
1981-02-27,13.432,NaN,0.997031,1.009773,1.062490,NaN,NaN,NaN
1981-02-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1981-03-02,13.622,NaN,NaN,1.055805,1.066552,NaN,NaN,NaN
1981-03-03,13.432,NaN,0.986052,1.018193,1.043505,NaN,NaN,NaN
1981-03-04,13.452,NaN,1.001489,1.018165,1.047500,NaN,NaN,NaN
1981-03-05,13.432,NaN,0.998513,1.010533,1.057471,NaN,NaN,NaN
1981-03-06,13.202,NaN,0.982877,0.979958,1.036915,NaN,NaN,NaN
1981-03-09,13.092,NaN,0.991668,0.974687,1.025055,NaN,NaN,NaN