In [233]:
ls

00. _wd - working day.txt
01. KRXworkingDay_from1980.csv
CSV/
Currency/
Currency_describe_directory_list.ipynb
KOR/
KRX반도체_SK하이닉스_KOSPI200.xlsx
Korean_stock_describe.ipynb
README.md
Ridge_baseline.ipynb
Taiwan/
Taiwan_describe_directory_list.ipynb
US/
US_stock_describe_list_final.ipynb
_Rhistory
bloomberg_dataprocessing-Copy1.ipynb
bloomberg_dataprocessing.ipynb
data_change_ver0.1.csv
data_change_ver0.2.csv
df_test.csv
df_test2.csv
economic_smc.csv
eda.ipynb
eda_from_change.ipynb
lasso_baseline.ipynb
list
list.csv
logistic_classifier_baseline.ipynb
new/
ols_baseline_regression.ipynb
preprocessing.ipynb
preprocessing.py
semiconductor_bloomberg_preprocessing.ipynb
semiconductor_feature_list_bloomberg.xlsx
total_data.csv
totaldata_preprocessing.ipynb
tree_based_regressor_baseline.ipynb

In [234]:
pwd

'/Users/mokpolar/Documents/GitHub/KRX_semiconductor_index_prediction'

In [235]:
import pandas as pd
import re
%matplotlib inline

In [19]:
eco = pd.read_csv('/Users/mokpolar/Downloads/bloomberg_raw/economic.csv')

In [20]:
eco.set_index('col0', inplace = True)

In [21]:
eco.head()

                col1  col2        col3  col4
col0
GDP CQOQ Index     0     1  03/31/1981   8.1
GDP CQOQ Index     0     1  06/30/1981  -2.9
GDP CQOQ Index     0     1  09/30/1981   4.9
GDP CQOQ Index     0     1  12/31/1981  -4.3
GDP CQOQ Index     0     1  03/31/1982  -6.1

In [22]:
economic = eco.loc[['GDP CQOQ Index',
'GDP CYOY Index',
'GDPCTOT% Index',
'GPDITOC% Index',
'GPGSTOC% Index',
'RGCDCIPI Index',
'GDP CUR$ Index',
'GDP CURY Index',
'GDP PIQQ Index',
'GDPCPCEC Index',
'CPI YOY Index',
'CPI XYOY Index',
'PCE DEFY Index',
'PCE CYOY Index',
'CPI CHNG Index',
'CPUPXCHG Index',
'FDIDFDMO Index',
'FDIDSGMO Index',
'FDIUFDYO Index',
'FDIUSGYO Index',
'USURTOT Index',
'USUDMAER Index',
'INJCJC Index',
'INJCSP Index',
'NFP TCH Index',
'NFP PCH Index',
'USMMMNCH Index',
'AWH TOTL Index',
'USWHTOT Index',
'USEMTOT Index',
'USEMNCHG Index',
'USERTOT Index',
'EMDINP1M Index',
'JOLTOPEN Index',
'JOLTHIRS Index',
'JOLTSEPS Index',
'CHALYOY% Index',
'ADP CHNG Index',
'USHEYOY Index',
'USHETOT% Index',
'ECI YOY Index',
'COSTNFR% Index',
'PRODNFR% Index',
'IP  YOY Index',
'IP  CHNG Index',
'CPTICHNG Index',
'TMNOCHNG Index',
'DGNOYOY Index',
'DGNOCHNG Index',
'MTIBCHNG Index',
'MWINCHNG Index',
'MGT2TB Index',
'MGT2MA Index',
'MGT2WH Index',
'MGT2WHDU Index',
'MGT2RE Index',
'IP Index',
'MTSLRL$ Index',
'AGWHTOTL Index',
'NFP T Index',
'USEMTOT Index',
'PIDSPINX Index',
'NAPMPMI Index',
'NAPMNMI Index',
'NAPMPRIC Index',
'MPMIUSCA Index',
'MPMIUSMA Index',
'MPMIUSSA Index',
'CFNAI Index',
'CFNAIMA3 Index',
'OUTFGAF Index',
'EMPRGBCI Index',
'RCHSINDX Index',
'CHPMINDX Index',
'MAPMINDX Index',
'OEUSKLAR Index',
'OEUSKLAP Index',
'LEI TOTL Index',
'LEI YOY Index',
'LEI CHNG Index',
'LEI AVGW Index',
'LEI WKIJ Index',
'LEI NWCN Index',
'NAPMNEWO Index',
'LEI MNO Index',
'LEI BP Index',
'LEI STKP Index',
'LEI LCI Index',
'LEI IRTE Index',
'LEI ACE Index',
'RSTAMOM Index',
'RSTAXMOM Index',
'RSTAYOY Index',
'RSTAXYOY Index',
'MBRXYOYW Index',
'SAARTOTL Index',
'SAARDTOT Index',
'CONCCONF Index',
'CONSSENT Index',
'COMFCOMF Index',
'COMFBTWR Index',
'PITLYOY Index',
'PITLCHNG Index',
'PCE CHY% Index',
'PCE CHNC Index',
'PIDSDPS Index',
'CICRTOT Index',
'EHCAUS Index',
'USCABAL Index',
'USTBTOT Index',
'USTBEXP Index',
'USTBIMP Index',
'USTBEXPY Index',
'USTBIMPY Index',
'IMP1YOY% Index',
'IMP1CHNG Index',
'FRNTTOTL Index',
'FRNTTNET Index',
'FDTR Index',
'USGG3M Index',
'USGG10YR Index',
'USTW$ Index',
'JNVNYOYS Index',
'JNVNIYOY Index',
'MPMIJPCA Index',
'MPMIJPMA Index',
'MPMIJPSA Index',
'CNGDPYOY Index',
'GDPNTTLY Index',
'CHEFTYOY Index',
'CNPPIY Index',
'CPMINDX Index',
'CPMINORD Index',
'CPMINEXO Index',
'CNCILI Index',
'CNFREXPY Index',
'CNFRIMPY Index',
'KOGDPYOY Index',
'KOGDPQOQ Index',
'KOECPRCY Index',
'KOECGCPY Index',
'KOECGVTY Index',
'KOECEXPY Index',
'KOECIMPY Index',
'KOECSPRQ Index',
'KOECGCSY Index',
'KOECSGVQ Index',
'KOECSEMQ Index',
'KOECSIMQ Index',
'KOECFCOY Index',
'KOECFCSY Index',
'OEKRN022 Index',
'KOGNICNY Index',
'KOGNICUY Index',
'KOGCGDPY Index',
'KOGCSTOQ Index',
'KODFTOTY Index',
'KOCPI Index',
'KOCPIYOY Index',
'KOCPIMOM Index',
'SKCITTL Index',
'SKCIYOY Index',
'SKCIMOM Index',
'KOCLLNS Index',
'KOPPI Index',
'KOPPIYOY Index',
'KOPPIMOM Index',
'KOEAUERS Index',
'KOEAEMPY Index',
'KOUETTY Index',
'KOEAPY Index',
'KOEAEPR Index',
'KOQEEYOY Index',
'KOWDR Index',
'KOULMGF Index',
'KOULMGFY Index',
'KOLPI Index',
'KOLPIY Index',
'SKLIOTAR Index',
'KOIPISA Index',
'KOIPIY Index',
'KOIPIMOM Index',
'KOIPMS Index',
'KOIPMY Index',
'KOIPMSM Index',
'KOPSIY Index',
'KOPIIY Index',
'KOIPMC Index',
'KOIPMCY Index',
'KOIPOPSM Index',
'KOIVCPEY Index',
'KOIVCCY Index',
'KOIVCONY Index',
'KOCGCGY Index',
'KOCGCGSM Index',
'KOSVTOTY Index',
'KOSVTOTM Index',
'KOVMPROD Index',
'KOBSMC Index',
'KOBSNMC Index',
'SKBSIC Index',
'SKBSICSA Index',
'MPMIKRMA Index',
'OEKRKLAR Index',
'OEKRKLAP Index',
'SKLILI Index',
'SKLILY Index',
'SKLILC Index',
'SKLICI Index',
'SKLIINVC Index',
'SKLICONE Index',
'SKLIMORD Index',
'SKLICONT Index',
'SKLINBAR Index',
'SKLIOTAR Index',
'SKLISPRC Index',
'SKLIINTR Index',
'SKLIIPAL Index',
'SKLICNST Index',
'SKLISVCI Index',
'SKLIWNRS Index',
'SKLISHPP Index',
'SKLIIMPT Index',
'SKLIEMPP Index',
'SKLILAP Index',
'SKLILAI Index',
'SKLINE Index',
'SKLICPY Index',
'KOBONTL Index',
'KOHSTR Index',
'KOHPTTL Index',
'KOHPTYOY Index',
'KOHCTTL Index',
'KOHCTYOY Index',
'KOBLTHML Index',
'KOBLTHMY Index',
'KOUHTTL Index',
'KORST Index',
'KORSTY Index',
'KODSDEPT Index',
'KODSDISC Index',
'KOVMTOTS Index',
'KOVMDOMS Index',
'KOVMEXPS Index',
'KOCCCSI Index',
'KOHOINC Index',
'KOHOINCY Index',
'KOHEUINY Index',
'KOHHD Index',
'KOHHDY Index',
'KOHHL Index',
'KOHHLY Index',
'EOKOS002 Index',
'KOBPCB Index',
'EHCAKRY Index',
'KOBPFIN Index',
'KOBPCA Index',
'KODIBAL Index',
'KOBPTB Index',
'KOTRBAL Index',
'KOEXTOT Index',
'KOIMTOT Index',
'KOEXTOTY Index',
'KOIMTOTY Index',
'KOEXPTI Index',
'KOEXPTIY Index',
'KOEXPTIM Index',
'KOIMPTI Index',
'KOIMPTIY Index',
'KOIMPTIM Index',
'KOFDIT Index',
'KOFDITY Index',
'KOELTOT Index',
'KOGFBAL Index',
'KOGFTEXP Index',
'KOGFTR Index',
'G7BBKORE Index',
'GDDBSOKO Index',
'KOMSMBY Index',
'KOMSM1Y Index',
'KOMSM2Y Index',
'KOMSM3Y Index',
'KOMSLY Index',
'KOMSM1FY Index',
'KOFETOT Index',
'KOFETOT% Index',
'KORP7D Index',
'KOCICOBA Index',
'KOCICONF Index',
'KRBO3M Index',
'KWCDC Curncy',
'GVSK10YR Index'], :]

In [23]:
eco.head()

                col1  col2        col3  col4
col0
GDP CQOQ Index     0     1  03/31/1981   8.1
GDP CQOQ Index     0     1  06/30/1981  -2.9
GDP CQOQ Index     0     1  09/30/1981   4.9
GDP CQOQ Index     0     1  12/31/1981  -4.3
GDP CQOQ Index     0     1  03/31/1982  -6.1

In [29]:
eco.set_index('col0', inplace = True)

In [24]:
eco.info()

<class 'pandas.core.frame.DataFrame'>
Index: 821348 entries, GDP CQOQ Index to IDR Curncy
Data columns (total 4 columns):
col1    821348 non-null int64
col2    821348 non-null int64
col3    821348 non-null object
col4    821348 non-null object
dtypes: int64(2), object(2)
memory usage: 51.3+ MB

In [26]:
economic.reset_index()

                  col0  col1  col2        col3   col4
0       GDP CQOQ Index     0     1  03/31/1981    8.1
1       GDP CQOQ Index     0     1  06/30/1981   -2.9
2       GDP CQOQ Index     0     1  09/30/1981    4.9
3       GDP CQOQ Index     0     1  12/31/1981   -4.3
4       GDP CQOQ Index     0     1  03/31/1982   -6.1
...                ...   ...   ...         ...    ...
148415  GVSK10YR Index     0     1  10/25/2019  1.685
148416  GVSK10YR Index     0     1  10/28/2019  1.777
148417  GVSK10YR Index     0     1  10/29/2019  1.766
148418  GVSK10YR Index     0     1  10/30/2019  1.744
148419  GVSK10YR Index     0     1  10/31/2019   1.73

[148420 rows x 5 columns]

In [ ]:
eco.reset_index(inplace = True)

In [ ]:
eco.to_csv('economic_smc.csv')

### --- 여기까지는 Column 뽑아내기 ---

In [236]:
eco = pd.read_csv('economic_smc.csv')

In [237]:
len(eco)

148420

In [238]:
eco.head()

             col0  col1  col2        col3  col4
0  GDP CQOQ Index     0     1  03/31/1981   8.1
1  GDP CQOQ Index     0     1  06/30/1981  -2.9
2  GDP CQOQ Index     0     1  09/30/1981   4.9
3  GDP CQOQ Index     0     1  12/31/1981  -4.3
4  GDP CQOQ Index     0     1  03/31/1982  -6.1

In [239]:
# 일단 m달린 데이터를 제거해버리자
def delete_m(c):
    if c[-1] == 'm':
        c = ' '
    else:
        pass
    return c

In [240]:
# M달린 데이터도 제거해버리자
def delete_M(c):
    if c[-1] == 'M':
        c = ' '
    else:
        pass
    return c

In [241]:
eco.head()

             col0  col1  col2        col3  col4
0  GDP CQOQ Index     0     1  03/31/1981   8.1
1  GDP CQOQ Index     0     1  06/30/1981  -2.9
2  GDP CQOQ Index     0     1  09/30/1981   4.9
3  GDP CQOQ Index     0     1  12/31/1981  -4.3
4  GDP CQOQ Index     0     1  03/31/1982  -6.1

In [243]:
# map + lambda 콤보로 이거 날리자 m , M 달린건 전부  ' ' 으로 변환
eco['col4'] = eco['col4'].map(lambda x: delete_m(x))

In [244]:
# ' '으로 만들어진거 전부 드롭
eco.drop(eco[eco['col4'] == ' '].index, axis = 0, inplace = True)

In [245]:
len(eco[eco['col4'] == ' '])

0

In [246]:
eco['col4'] = eco['col4'].map(lambda x: delete_M(x))

In [247]:
eco.drop(eco[eco['col4'] == ' '].index, axis = 0, inplace = True)

In [248]:
len(eco[eco['col4'] == ' '])

0

In [249]:
# 이상한 거 다빠졌으니까 numeric으로 변환
eco['col4'] = pd.to_numeric(eco['col4'])

In [250]:
# 애초에 그런게 별로 안되었으므로 빠진 데이터는 몇개 없다. 
len(eco)

148332

In [251]:
# col3 type datetime으로 만들기 
eco['col3'] = pd.to_datetime(eco['col3'])

In [252]:
eco['col4'].unique()

array([ 8.1  , -2.9  ,  4.9  , ...,  1.528,  1.647,  1.744])

In [253]:
# 변수 종류는 289개
len(eco['col0'].unique())

289

In [254]:
# 변수별로 데이터 갯수 확인 필요 뭐야 이거 시박 다 다르네
for i, j in enumerate(eco['col0'].unique()):
    print(i, eco['col0'].unique()[i], len(eco[eco['col0'] == j]))

0 GDP CQOQ Index 152
1 GDP CYOY Index 152
2 GDPCTOT% Index 152
3 GPDITOC% Index 152
4 GPGSTOC% Index 152
5 RGCDCIPI Index 80
6 GDP CUR$ Index 152
7 GDP CURY Index 152
8 GDP PIQQ Index 152
9 GDPCPCEC Index 152
10 CPI YOY Index 455
11 CPI XYOY Index 455
12 PCE DEFY Index 455
13 PCE CYOY Index 455
14 CPI CHNG Index 455
15 CPUPXCHG Index 455
16 FDIDFDMO Index 118
17 FDIDSGMO Index 113
18 FDIUFDYO Index 107
19 FDIUSGYO Index 107
20 USURTOT Index 456
21 USUDMAER Index 300
22 INJCJC Index 1983
23 INJCSP Index 1982
24 NFP TCH Index 456
25 NFP PCH Index 456
26 USMMMNCH Index 456
27 AWH TOTL Index 164
28 USWHTOT Index 456
29 USEMTOT Index 912
30 USEMNCHG Index 456
31 USERTOT Index 456
32 EMDINP1M Index 336
33 JOLTOPEN Index 215
34 JOLTHIRS Index 215
35 JOLTSEPS Index 215
36 CHALYOY% Index 228
37 ADP CHNG Index 210
38 USHEYOY Index 456
39 USHETOT% Index 456
40 ECI YOY Index 72
41 COSTNFR% Index 151
42 PRODNFR% Index 151
43 IP  YOY Index 455
44 IP  CHNG Index 455
45 CPTICHNG Index 455
46 TMNOCHNG Index 455
47 DGNOYOY Index 322
48 DGNOCHNG Index 322
49 MTIBCHNG Index 454
50 MWINCHNG Index 323
51 MGT2TB Index 454
52 MGT2MA Index 323
53 MGT2WH Index 322
54 MGT2WHDU Index 322
55 MGT2RE Index 454
56 IP Index 455
57 MTSLRL$ Index 262
58 AGWHTOTL Index 164
59 NFP T Index 456
60 PIDSPINX Index 455
61 NAPMPMI Index 456
62 NAPMNMI Index 257
63 NAPMPRIC Index 456
64 MPMIUSCA Index 37
65 MPMIUSMA Index 36
66 MPMIUSSA Index 37
67 CFNAI Index 455
68 CFNAIMA3 Index 455
69 OUTFGAF Index 456
70 EMPRGBCI Index 216
71 RCHSINDX Index 302
72 CHPMINDX Index 456
73 MAPMINDX Index 238
74 OEUSKLAR Index 452
75 OEUSKLAP Index 452
76 LEI TOTL Index 455
77 LEI YOY Index 455
78 LEI CHNG Index 455
79 LEI AVGW Index 455
80 LEI WKIJ Index 456
81 LEI NWCN Index 455
82 NAPMNEWO Index 456
83 LEI MNO Index 455
84 LEI BP Index 455
85 LEI STKP Index 455
86 LEI LCI Index 343
87 LEI IRTE Index 455
88 LEI ACE Index 455
89 RSTAMOM Index 322
90 RSTAXMOM Index 322
91 RSTAYOY Index 311
92 RSTAXYOY Index 311
93 MBRXYOYW Index 265
94 SAARTOTL Index 456
95 SAARDTOT Index 437
96 CONCCONF Index 456
97 CONSSENT Index 456
98 COMFCOMF Index 1726
99 COMFBTWR Index 318
100 PITLYOY Index 455
101 PITLCHNG Index 455
102 PCE CHY% Index 227
103 PCE CHNC Index 297
104 PIDSDPS Index 455
105 CICRTOT Index 454
106 EHCAUS Index 151
107 USCABAL Index 151
108 USTBTOT Index 322
109 USTBEXP Index 322
110 USTBIMP Index 322
111 USTBEXPY Index 310
112 USTBIMPY Index 310
113 IMP1YOY% Index 373
114 IMP1CHNG Index 359
115 FRNTTOTL Index 454
116 FRNTTNET Index 454
117 FDTR Index 9747
118 USGG3M Index 9786
119 USGG10YR Index 9790
120 USTW$ Index 9591
121 JNVNYOYS Index 71
122 JNVNIYOY Index 151
123 MPMIJPCA Index 37
124 MPMIJPMA Index 36
125 MPMIJPSA Index 37
126 CNGDPYOY Index 108
127 GDPNTTLY Index 38
128 CHEFTYOY Index 311
129 CNPPIY Index 242
130 CPMINDX Index 178
131 CPMINORD Index 178
132 CPMINEXO Index 178
133 CNCILI Index 333
134 CNFREXPY Index 335
135 CNFRIMPY Index 335
136 KOGDPYOY Index 76
137 KOGDPQOQ Index 76
138 KOECPRCY Index 152
139 KOECGCPY Index 152
140 KOECGVTY Index 152
141 KOECEXPY Index 152
142 KOECIMPY Index 152
143 KOECSPRQ Index 152
144 KOECGCSY Index 152
145 KOECSGVQ Index 152
146 KOECSEMQ Index 152
147 KOECSIMQ Index 152
148 KOECFCOY Index 152
149 KOECFCSY Index 152
150 OEKRN022 Index 152
151 KOGNICNY Index 151
152 KOGNICUY Index 151
153 KOGCGDPY Index 151
154 KOGCSTOQ Index 151
155 KODFTOTY Index 151
156 KOCPI Index 456
157 KOCPIYOY Index 456
158 KOCPIMOM Index 456
159 SKCITTL Index 456
160 SKCIYOY Index 456
161 SKCIMOM Index 456
162 KOCLLNS Index 288
163 KOPPI Index 455
164 KOPPIYOY Index 455
165 KOPPIMOM Index 455
166 KOEAUERS Index 234
167 KOEAEMPY Index 222
168 KOUETTY Index 425
169 KOEAPY Index 222
170 KOEAEPR Index 234
171 KOQEEYOY Index 298
172 KOWDR Index 50
173 KOULMGF Index 46
174 KOULMGFY Index 42
175 KOLPI Index 46
176 KOLPIY Index 42
177 SKLIOTAR Index 618
178 KOIPISA Index 455
179 KOIPIY Index 455
180 KOIPIMOM Index 455
181 KOIPMS Index 455
182 KOIPMY Index 455
183 KOIPMSM Index 455
184 KOPSIY Index 455
185 KOPIIY Index 455
186 KOIPMC Index 455
187 KOIPMCY Index 455
188 KOIPOPSM Index 455
189 KOIVCPEY Index 275
190 KOIVCCY Index 245
191 KOIVCONY Index 455
192 KOCGCGY Index 275
193 KOCGCGSM Index 286
194 KOSVTOTY Index 227
195 KOSVTOTM Index 226
196 KOVMPROD Index 276
197 KOBSMC Index 202
198 KOBSNMC Index 202
199 SKBSIC Index 456
200 SKBSICSA Index 372
201 MPMIKRMA Index 36
202 OEKRKLAR Index 344
203 OEKRKLAP Index 332
204 SKLILI Index 455
205 SKLILY Index 455
206 SKLILC Index 455
207 SKLICI Index 455
208 SKLIINVC Index 347
209 SKLICONE Index 238
210 SKLIMORD Index 239
211 SKLICONT Index 347
212 SKLINBAR Index 287
213 SKLISPRC Index 335
214 SKLIINTR Index 287
215 SKLIIPAL Index 347
216 SKLICNST Index 251
217 SKLISVCI Index 239
218 SKLIWNRS Index 347
219 SKLISHPP Index 347
220 SKLIIMPT Index 347
221 SKLIEMPP Index 347
222 SKLILAP Index 347
223 SKLILAI Index 347
224 SKLINE Index 201
225 SKLICPY Index 201
226 KOBONTL Index 215
227 KOHSTR Index 13
228 KOHPTTL Index 396
229 KOHPTYOY Index 384
230 KOHCTTL Index 241
231 KOHCTYOY Index 229
232 KOBLTHML Index 70
233 KOBLTHMY Index 58
234 KOUHTTL Index 220
235 KORST Index 177
236 KORSTY Index 165
237 KODSDEPT Index 201
238 KODSDISC Index 201
239 KOVMTOTS Index 276
240 KOVMDOMS Index 276
241 KOVMEXPS Index 276
242 KOCCCSI Index 136
243 KOHOINC Index 66
244 KOHOINCY Index 62
245 KOHEUINY Index 111
246 KOHHD Index 67
247 KOHHDY Index 63
248 KOHHL Index 67
249 KOHHLY Index 63
250 KOBPCB Index 454
251 EHCAKRY Index 38
252 KOBPFIN Index 454
253 KOBPCA Index 454
254 KODIBAL Index 454
255 KOBPTB Index 454
256 KOTRBAL Index 350
257 KOEXTOT Index 456
258 KOIMTOT Index 456
259 KOEXTOTY Index 456
260 KOIMTOTY Index 456
261 KOEXPTI Index 455
262 KOEXPTIY Index 455
263 KOEXPTIM Index 455
264 KOIMPTI Index 455
265 KOIMPTIY Index 455
266 KOIMPTIM Index 455
267 KOFDIT Index 67
268 KOFDITY Index 67
269 KOELTOT Index 96
270 KOGFBAL Index 227
271 KOGFTEXP Index 227
272 KOGFTR Index 227
273 G7BBKORE Index 38
274 GDDBSOKO Index 15
275 KOMSMBY Index 454
276 KOMSM1Y Index 454
277 KOMSM2Y Index 382
278 KOMSM3Y Index 382
279 KOMSLY Index 274
280 KOMSM1FY Index 454
281 KOFETOT Index 456
282 KOFETOT% Index 456
283 KORP7D Index 5860
284 KOCICOBA Index 117
285 KOCICONF Index 117
286 KRBO3M Index 3783
287 KWCDC Curncy 6229
288 GVSK10YR Index 4451